// ============================================================
// lib/library-api.ts — Bibliothèque islamique numérique
// Équivalent web de المكتبة الشاملة (Shamela) + تراث (Turath)
// ⚠️  Les textes classiques sont sacrés — jamais modifier
// ⚠️  Les résumés générés par IA sont labellisés "Résumé non officiel"
// ============================================================

// ── Types ────────────────────────────────────────────────────

export interface LibraryCategory {
  id: string
  nameAr: string
  nameFr: string
  icon: string
  bookCount: number
  description: string
}

export interface LibraryBook {
  id: string
  titleAr: string
  titleFr?: string
  authorAr: string
  authorFr?: string
  categoryId: string
  pages?: number
  volumes?: number
  year?: string           // ex: '310 هـ' = année de décès de l'auteur
  publisher?: string
  description?: string
  incipit?: string        // Début du livre en arabe (texte sacré)
  shamela_id?: number | null
  openlib_id?: string
  isOpenAccess: boolean
  isFeatured?: boolean
}

// ── Catégories ───────────────────────────────────────────────

export const LIBRARY_CATEGORIES: LibraryCategory[] = [
  {
    id: 'quran',
    nameAr: 'القرآن وعلومه',
    nameFr: 'Coran et ses sciences',
    icon: '📖',
    bookCount: 1240,
    description: 'Tafsir, sciences du Coran, qira\'at, i\'jaz al-Qur\'an, etc.',
  },
  {
    id: 'hadith',
    nameAr: 'الحديث وعلومه',
    nameFr: 'Hadith et ses sciences',
    icon: '📜',
    bookCount: 890,
    description: 'Kutub al-sitta, musanafat, sharh, rijal, jarh wa ta\'dil, etc.',
  },
  {
    id: 'fiqh',
    nameAr: 'الفقه وأصوله',
    nameFr: 'Fiqh et Usul al-Fiqh',
    icon: '⚖️',
    bookCount: 2100,
    description: 'Les 4 madhahib : Hanafi, Maliki, Shafi\'i, Hanbali et usul al-fiqh',
  },
  {
    id: 'aqida',
    nameAr: 'العقيدة',
    nameFr: 'Aqida (Théologie)',
    icon: '🌙',
    bookCount: 560,
    description: 'Tawhid, Ash\'ari, Maturidi, Athari, Kalam, Milal wa Nihal',
  },
  {
    id: 'sira',
    nameAr: 'السيرة والتاريخ',
    nameFr: 'Sira et Histoire',
    icon: '🏛️',
    bookCount: 430,
    description: 'Sira du Prophète ﷺ, histoire islamique, biographies, tabaqat',
  },
  {
    id: 'tasawwuf',
    nameAr: 'التزكية والأخلاق',
    nameFr: 'Purification & Éthique',
    icon: '🌿',
    bookCount: 320,
    description: 'Ihya\' Ulum al-Din, Rissala Qushayriyya, zuhd, mawaqif, adab',
  },
  {
    id: 'lughah',
    nameAr: 'اللغة العربية',
    nameFr: 'Langue arabe',
    icon: '✍️',
    bookCount: 780,
    description: 'Grammaire (nahw), morphologie (sarf), rhétorique (balagha), lexique',
  },
  {
    id: 'general',
    nameAr: 'متنوع',
    nameFr: 'Divers',
    icon: '📚',
    bookCount: 2500,
    description: 'Encyclopédies, usul al-fiqh, philosophie, maqasid, anthologies',
  },
]

// ── Livres — 100+ œuvres curatées ───────────────────────────

export const FEATURED_BOOKS: LibraryBook[] = [

  // ══════════════════════════════════════════════
  // QURAN & SCIENCES CORANIQUES
  // ══════════════════════════════════════════════
  {
    id: 'tafsir-tabari',
    titleAr: 'جامع البيان في تأويل القرآن',
    titleFr: "Jami' al-Bayan (Tafsir al-Tabari)",
    authorAr: 'ابن جرير الطبري',
    authorFr: 'Muhammad ibn Jarir al-Tabari',
    categoryId: 'quran',
    volumes: 30,
    year: '310 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 1,
    description: "Le plus grand tafsir encyclopédique de l'islam — fondateur de la méthode bi'l-ma'thur.",
    incipit: 'الحمد لله الذي أرسل رسوله محمداً بالهدى ودين الحق',
  },
  {
    id: 'tafsir-ibn-kathir',
    titleAr: 'تفسير القرآن العظيم',
    titleFr: 'Tafsir Ibn Kathir',
    authorAr: 'ابن كثير الدمشقي',
    authorFr: 'Ismail ibn Kathir al-Dimashqi',
    categoryId: 'quran',
    volumes: 8,
    year: '774 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 2,
    description: "Le tafsir le plus utilisé dans le monde sunnite — méthode bi'l-ma'thur claire et accessible.",
    incipit: 'هذا تفسير القرآن العظيم نسأل الله العظيم أن ينفع به',
  },
  {
    id: 'tafsir-jalalayn',
    titleAr: 'تفسير الجلالين',
    titleFr: 'Tafsir al-Jalalayn',
    authorAr: 'جلال الدين المحلي وجلال الدين السيوطي',
    authorFr: 'Jalal al-Din al-Mahalli & Jalal al-Din al-Suyuti',
    categoryId: 'quran',
    pages: 600,
    year: '911 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 3,
    description: "Tafsir concis et dense — le plus étudié dans les écoles islamiques traditionnelles.",
    incipit: 'بسم الله الرحمن الرحيم الحمد لله على نعمه الجزيلة',
  },
  {
    id: 'tafsir-muyassar',
    titleAr: 'التفسير الميسر',
    titleFr: 'Al-Tafsir al-Muyassar',
    authorAr: 'مجمع الملك فهد لطباعة المصحف الشريف',
    authorFr: 'Complexe du Roi Fahd',
    categoryId: 'quran',
    pages: 604,
    isOpenAccess: true,
    description: "Tafsir simplifié du Complexe du Roi Fahd — recommandé pour débutants et grand public.",
  },
  {
    id: 'tafsir-saadi',
    titleAr: 'تيسير الكريم الرحمن في تفسير كلام المنان',
    titleFr: "Tafsir al-Sa'di",
    authorAr: 'عبد الرحمن بن ناصر السعدي',
    authorFr: 'Abd al-Rahman ibn Nasir al-Sa\'di',
    categoryId: 'quran',
    volumes: 1,
    year: '1376 هـ',
    isOpenAccess: true,
    shamela_id: 4,
    description: "Tafsir moderne en un volume — clarté et profondeur spirituelle exceptionnelles.",
  },
  {
    id: 'tafsir-qurtubi',
    titleAr: 'الجامع لأحكام القرآن',
    titleFr: 'Tafsir al-Qurtubi',
    authorAr: 'أبو عبد الله القرطبي',
    authorFr: 'Abu Abdallah al-Qurtubi',
    categoryId: 'quran',
    volumes: 20,
    year: '671 هـ',
    isOpenAccess: true,
    shamela_id: 5,
    description: "Tafsir de référence malékite — riche en rulings juridiques et questions de fiqh.",
  },
  {
    id: 'itqan-ulum-quran',
    titleAr: 'الإتقان في علوم القرآن',
    titleFr: "Al-Itqan fi 'Ulum al-Qur'an",
    authorAr: 'جلال الدين السيوطي',
    authorFr: 'Jalal al-Din al-Suyuti',
    categoryId: 'quran',
    volumes: 2,
    year: '911 هـ',
    isOpenAccess: true,
    shamela_id: 6,
    description: "Encyclopédie des sciences coraniques — 80 disciplines étudiées de manière exhaustive.",
  },
  {
    id: 'burhan-ulum-quran',
    titleAr: 'البرهان في علوم القرآن',
    titleFr: "Al-Burhan fi 'Ulum al-Qur'an",
    authorAr: 'بدر الدين الزركشي',
    authorFr: 'Badr al-Din al-Zarkashi',
    categoryId: 'quran',
    volumes: 4,
    year: '794 هـ',
    isOpenAccess: true,
    shamela_id: 7,
    description: "Traité fondateur des sciences coraniques — précède l'Itqan et en est la source principale.",
  },
  {
    id: 'manahil-irfan',
    titleAr: 'مناهل العرفان في علوم القرآن',
    titleFr: "Manahil al-'Irfan",
    authorAr: 'محمد عبد العظيم الزرقاني',
    authorFr: 'Muhammad Abd al-Azim al-Zarqani',
    categoryId: 'quran',
    volumes: 2,
    year: '1367 هـ',
    isOpenAccess: true,
    description: "Ouvrage moderne de référence sur les sciences du Coran — utilisé dans les universités islamiques.",
  },

  // ══════════════════════════════════════════════
  // HADITH ET SES SCIENCES
  // ══════════════════════════════════════════════
  {
    id: 'sahih-bukhari',
    titleAr: 'الجامع المسند الصحيح المختصر',
    titleFr: 'Sahih al-Bukhari',
    authorAr: 'محمد بن إسماعيل البخاري',
    authorFr: 'Muhammad ibn Ismail al-Bukhari',
    categoryId: 'hadith',
    volumes: 9,
    year: '256 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 1,
    description: "Le recueil le plus authentique de hadiths après le Coran — 7275 hadiths sélectionnés parmi 600 000.",
    incipit: 'إنما الأعمال بالنيات وإنما لكل امرئ ما نوى',
  },
  {
    id: 'sahih-muslim',
    titleAr: 'المسند الصحيح المختصر بنقل العدل عن العدل',
    titleFr: 'Sahih Muslim',
    authorAr: 'مسلم بن الحجاج النيسابوري',
    authorFr: 'Muslim ibn al-Hajjaj al-Nisaburi',
    categoryId: 'hadith',
    volumes: 8,
    year: '261 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 2,
    description: "Deuxième recueil le plus authentique — organisation thématique rigoureuse, 3033 hadiths.",
  },
  {
    id: 'sunan-abi-dawud',
    titleAr: 'سنن أبي داود',
    titleFr: 'Sunan Abi Dawud',
    authorAr: 'أبو داود السجستاني',
    authorFr: 'Abu Dawud al-Sijistani',
    categoryId: 'hadith',
    volumes: 5,
    year: '275 هـ',
    isOpenAccess: true,
    shamela_id: 3,
    description: "Spécialisé dans les hadiths juridiques — référence indispensable pour le fiqh.",
  },
  {
    id: 'jami-tirmidhi',
    titleAr: 'الجامع الكبير (سنن الترمذي)',
    titleFr: "Jami' al-Tirmidhi",
    authorAr: 'أبو عيسى الترمذي',
    authorFr: "Abu 'Isa al-Tirmidhi",
    categoryId: 'hadith',
    volumes: 5,
    year: '279 هـ',
    isOpenAccess: true,
    shamela_id: 4,
    description: "Recueil avec commentaires sur l'authenticité — premier à classer les hadiths par degré.",
  },
  {
    id: 'sunan-nasai',
    titleAr: 'السنن الكبرى',
    titleFr: 'Sunan al-Nasa\'i',
    authorAr: 'أحمد بن شعيب النسائي',
    authorFr: "Ahmad ibn Shu'ayb al-Nasa'i",
    categoryId: 'hadith',
    volumes: 8,
    year: '303 هـ',
    isOpenAccess: true,
    shamela_id: 5,
    description: "Réputé pour la rigueur de sa critique des narrations — critères les plus stricts après Bukhari.",
  },
  {
    id: 'sunan-ibn-majah',
    titleAr: 'سنن ابن ماجه',
    titleFr: 'Sunan Ibn Majah',
    authorAr: 'محمد بن يزيد بن ماجه القزويني',
    authorFr: 'Muhammad ibn Yazid Ibn Majah al-Qazwini',
    categoryId: 'hadith',
    volumes: 2,
    year: '273 هـ',
    isOpenAccess: true,
    shamela_id: 6,
    description: "Sixième des kutub al-sitta — contient des hadiths supplémentaires non présents ailleurs.",
  },
  {
    id: 'muwatta-malik',
    titleAr: 'موطأ مالك',
    titleFr: 'Muwatta\' de Malik',
    authorAr: 'مالك بن أنس الأصبحي',
    authorFr: 'Malik ibn Anas al-Asbahi',
    categoryId: 'hadith',
    volumes: 2,
    year: '179 هـ',
    isOpenAccess: true,
    shamela_id: 7,
    description: "Le premier grand recueil canonique — combinaison de hadiths et de fiqh malékite.",
    incipit: 'يحيى بن يحيى الليثي عن مالك بن أنس',
  },
  {
    id: 'musnad-ahmad',
    titleAr: 'المسند',
    titleFr: "Musnad d'Ahmad ibn Hanbal",
    authorAr: 'أحمد بن محمد بن حنبل الشيباني',
    authorFr: 'Ahmad ibn Muhammad ibn Hanbal al-Shaybani',
    categoryId: 'hadith',
    volumes: 50,
    year: '241 هـ',
    isOpenAccess: true,
    shamela_id: 8,
    description: "Le plus grand musnad — 30 000 hadiths classés par rapporteur (sahabi), base documentaire unique.",
  },
  {
    id: 'riyadh-salihin',
    titleAr: 'رياض الصالحين',
    titleFr: 'Riyadh al-Salihin',
    authorAr: 'يحيى بن شرف النووي',
    authorFr: 'Yahya ibn Sharaf al-Nawawi',
    categoryId: 'hadith',
    pages: 600,
    year: '676 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 9,
    description: "Anthologie thématique accessible — idéale pour la lecture quotidienne, 1896 hadiths.",
  },
  {
    id: 'arbaun-nawawiyya',
    titleAr: 'الأربعون النووية',
    titleFr: 'Les 40 hadiths de al-Nawawi',
    authorAr: 'يحيى بن شرف النووي',
    authorFr: 'Yahya ibn Sharaf al-Nawawi',
    categoryId: 'hadith',
    pages: 80,
    year: '676 هـ',
    isOpenAccess: true,
    shamela_id: 10,
    description: "42 hadiths fondateurs de l'islam — enseignés dans le monde entier, base de toute éducation islamique.",
    incipit: 'إنما الأعمال بالنيات وإنما لكل امرئ ما نوى',
  },
  {
    id: 'bulugh-maram',
    titleAr: 'بلوغ المرام من أدلة الأحكام',
    titleFr: 'Bulugh al-Maram',
    authorAr: 'ابن حجر العسقلاني',
    authorFr: 'Ibn Hajar al-Asqalani',
    categoryId: 'hadith',
    pages: 450,
    year: '852 هـ',
    isOpenAccess: true,
    shamela_id: 11,
    description: "Recueil de hadiths juridiques avec indications sur leur authenticité — référence pour le fiqh hadith.",
  },
  {
    id: 'mishkat-masabih',
    titleAr: 'مشكاة المصابيح',
    titleFr: 'Mishkat al-Masabih',
    authorAr: 'محمد بن عبد الله الخطيب التبريزي',
    authorFr: 'Muhammad al-Khatib al-Tabrizi',
    categoryId: 'hadith',
    volumes: 3,
    year: '741 هـ',
    isOpenAccess: true,
    shamela_id: 12,
    description: "Compilation thématique de hadiths extraits des kutub al-sitta — complément et enrichissement.",
  },

  // ══════════════════════════════════════════════
  // FIQH ET USUL AL-FIQH
  // ══════════════════════════════════════════════
  {
    id: 'majmou-nawawi',
    titleAr: 'المجموع شرح المهذب',
    titleFr: 'Al-Majmu\' Sharh al-Muhadhdhab',
    authorAr: 'يحيى بن شرف النووي',
    authorFr: 'Yahya ibn Sharaf al-Nawawi',
    categoryId: 'fiqh',
    volumes: 21,
    year: '676 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 20,
    description: "L'encyclopédie du fiqh shafi'i — l'œuvre juridique la plus exhaustive jamais produite.",
  },
  {
    id: 'mughni-ibn-qudama',
    titleAr: 'المغني',
    titleFr: "Al-Mughni d'Ibn Qudama",
    authorAr: 'موفق الدين ابن قدامة المقدسي',
    authorFr: 'Muwaffaq al-Din Ibn Qudama al-Maqdisi',
    categoryId: 'fiqh',
    volumes: 15,
    year: '620 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 21,
    description: "L'encyclopédie du fiqh hanbali — droit comparé des quatre madhahib à chaque chapitre.",
  },
  {
    id: 'bidayat-mujtahid',
    titleAr: 'بداية المجتهد ونهاية المقتصد',
    titleFr: 'Bidayat al-Mujtahid',
    authorAr: 'ابن رشد القرطبي',
    authorFr: 'Ibn Rushd al-Qurtubi (Averroès fils)',
    categoryId: 'fiqh',
    volumes: 2,
    year: '595 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 22,
    description: "Droit comparé des 4 madhahib — méthode rationaliste unique, référence des juristes comparatistes.",
  },
  {
    id: 'fiqh-sunnah',
    titleAr: 'فقه السنة',
    titleFr: 'Fiqh al-Sunnah',
    authorAr: 'سيد سابق',
    authorFr: 'Sayyid Sabiq',
    categoryId: 'fiqh',
    volumes: 3,
    year: '1420 هـ',
    isOpenAccess: true,
    shamela_id: 23,
    description: "Référence fiqh moderne accessible — basée sur les preuves textuelles, très répandu dans le monde arabe.",
  },
  {
    id: 'fiqh-mazahib-arba',
    titleAr: 'الفقه على المذاهب الأربعة',
    titleFr: 'Fiqh sur les quatre madhahib',
    authorAr: 'عبد الرحمن الجزيري',
    authorFr: 'Abd al-Rahman al-Jaziri',
    categoryId: 'fiqh',
    volumes: 4,
    year: '1360 هـ',
    isOpenAccess: true,
    shamela_id: 24,
    description: "Comparaison systématique des 4 écoles juridiques chapitre par chapitre — outil indispensable.",
  },
  {
    id: 'minhaj-talibin',
    titleAr: 'منهاج الطالبين وعمدة المفتين',
    titleFr: 'Minhaj al-Talibin',
    authorAr: 'يحيى بن شرف النووي',
    authorFr: 'Yahya ibn Sharaf al-Nawawi',
    categoryId: 'fiqh',
    pages: 450,
    year: '676 هـ',
    isOpenAccess: true,
    shamela_id: 25,
    description: "Manuel de référence du madhab shafi'i — base de la fatwa shafi'ite jusqu'à nos jours.",
  },
  {
    id: 'hashiya-ibn-abidin',
    titleAr: 'رد المحتار على الدر المختار (حاشية ابن عابدين)',
    titleFr: 'Hashiya Ibn Abidin',
    authorAr: 'محمد أمين ابن عابدين',
    authorFr: 'Muhammad Amin Ibn Abidin',
    categoryId: 'fiqh',
    volumes: 10,
    year: '1252 هـ',
    isOpenAccess: true,
    shamela_id: 26,
    description: "L'œuvre maîtresse du fiqh hanafite tardif — référence ultime de l'école hanafite ottomane.",
  },
  {
    id: 'sharh-kabir-dardir',
    titleAr: 'الشرح الكبير على مختصر خليل',
    titleFr: 'Al-Sharh al-Kabir de al-Dardir',
    authorAr: 'أحمد بن محمد الدردير',
    authorFr: 'Ahmad ibn Muhammad al-Dardir',
    categoryId: 'fiqh',
    volumes: 4,
    year: '1201 هـ',
    isOpenAccess: true,
    shamela_id: 27,
    description: "Commentaire monumental du Mukhtasar Khalil — référence du fiqh malékite dans le Maghreb.",
  },
  {
    id: 'rawda-talibin',
    titleAr: 'روضة الطالبين وعمدة المفتين',
    titleFr: 'Rawdat al-Talibin',
    authorAr: 'يحيى بن شرف النووي',
    authorFr: 'Yahya ibn Sharaf al-Nawawi',
    categoryId: 'fiqh',
    volumes: 12,
    year: '676 هـ',
    isOpenAccess: true,
    shamela_id: 28,
    description: "Synthèse du fiqh shafi'i en 12 volumes — entre le Muhadhdhab et le Minhaj al-Talibin.",
  },
  {
    id: 'umdat-fiqh',
    titleAr: 'عمدة الفقه',
    titleFr: "Umdat al-Fiqh d'Ibn Qudama",
    authorAr: 'ابن قدامة المقدسي',
    authorFr: 'Ibn Qudama al-Maqdisi',
    categoryId: 'fiqh',
    pages: 280,
    year: '620 هـ',
    isOpenAccess: true,
    shamela_id: 29,
    description: "Introduction au fiqh hanbali — concis, étudié dans les madrasas comme texte d'initiation.",
  },
  {
    id: 'zad-mustaqni',
    titleAr: 'زاد المستقنع في اختصار المقنع',
    titleFr: 'Zad al-Mustaqni',
    authorAr: 'شرف الدين الحجاوي',
    authorFr: 'Sharaf al-Din al-Hajawi',
    categoryId: 'fiqh',
    pages: 300,
    year: '968 هـ',
    isOpenAccess: true,
    shamela_id: 30,
    description: "Matn de référence hanbali — parmi les textes les plus enseignés en Arabie Saoudite.",
  },
  {
    id: 'mukhtasar-fiqhi-ibn-arafa',
    titleAr: 'المختصر الفقهي لابن عرفة',
    titleFr: "Al-Mukhtasar al-Fiqhi d'Ibn Arafa",
    authorAr: 'محمد بن محمد ابن عرفة الورغمي',
    authorFr: 'Muhammad ibn Muhammad Ibn Arafa al-Warghmi',
    categoryId: 'fiqh',
    volumes: 3,
    year: '803 هـ',
    isOpenAccess: true,
    description: "Résumé encyclopédique du fiqh malékite — référence savante de l'école tunisienne.",
  },

  // ══════════════════════════════════════════════
  // AQIDA (THÉOLOGIE)
  // ══════════════════════════════════════════════
  {
    id: 'aqida-tahawiyya',
    titleAr: 'العقيدة الطحاوية',
    titleFr: "Al-'Aqida al-Tahawiyya",
    authorAr: 'أبو جعفر الطحاوي',
    authorFr: 'Abu Ja\'far al-Tahawi',
    categoryId: 'aqida',
    pages: 120,
    year: '321 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 40,
    description: "Le texte de référence en aqida pour les trois grandes écoles — 13 siècles d'autorité.",
    incipit: 'هذا ذكر بيان عقيدة أهل السنة والجماعة على مذهب فقهاء الملة',
  },
  {
    id: 'aqida-wasitiyya',
    titleAr: 'العقيدة الواسطية',
    titleFr: "Al-'Aqida al-Wasitiyya",
    authorAr: 'أحمد بن تيمية الحراني',
    authorFr: 'Ahmad ibn Taymiyya al-Harrani',
    categoryId: 'aqida',
    pages: 80,
    year: '728 هـ',
    isOpenAccess: true,
    shamela_id: 41,
    description: "Exposé fondamental de l'aqida athariyya — texte concis d'une densité théologique remarquable.",
  },
  {
    id: 'lum-at-itiqad',
    titleAr: 'لمعة الاعتقاد',
    titleFr: "Lum'at al-I'tiqad",
    authorAr: 'ابن قدامة المقدسي',
    authorFr: 'Ibn Qudama al-Maqdisi',
    categoryId: 'aqida',
    pages: 60,
    year: '620 هـ',
    isOpenAccess: true,
    shamela_id: 42,
    description: "Texte d'initiation à l'aqida athariyya — étudié dans les madrasas du monde hanbali.",
  },
  {
    id: 'sharh-aqida-tahawiyya',
    titleAr: 'شرح العقيدة الطحاوية',
    titleFr: "Sharh al-'Aqida al-Tahawiyya",
    authorAr: 'ابن أبي العز الحنفي',
    authorFr: 'Ibn Abi al-Izz al-Hanafi',
    categoryId: 'aqida',
    pages: 600,
    year: '792 هـ',
    isOpenAccess: true,
    shamela_id: 43,
    description: "Commentaire détaillé de la Tahawiyya — considéré comme le meilleur sharh de ce texte.",
  },
  {
    id: 'kitab-tawhid-ibn-khuzayma',
    titleAr: 'كتاب التوحيد',
    titleFr: "Kitab al-Tawhid d'Ibn Khuzayma",
    authorAr: 'ابن خزيمة النيسابوري',
    authorFr: 'Muhammad ibn Khuzayma al-Nisaburi',
    categoryId: 'aqida',
    volumes: 2,
    year: '311 هـ',
    isOpenAccess: true,
    description: "Traité de théologie par l'un des plus grands muhaddithun — méthode athariyya basée sur les textes.",
  },
  {
    id: 'kitab-tawhid-ibn-abdelwahhab',
    titleAr: 'كتاب التوحيد الذي هو حق الله على العبيد',
    titleFr: "Kitab al-Tawhid de Muhammad ibn Abd al-Wahhab",
    authorAr: 'محمد بن عبد الوهاب التميمي',
    authorFr: 'Muhammad ibn Abd al-Wahhab al-Tamimi',
    categoryId: 'aqida',
    pages: 200,
    year: '1206 هـ',
    isOpenAccess: true,
    shamela_id: 44,
    description: "Texte central du mouvement de réforme wahhabite — enseigné dans les écoles du Golfe.",
  },
  {
    id: 'ibana-ashari',
    titleAr: 'الإبانة عن أصول الديانة',
    titleFr: "Al-Ibana de al-Ash'ari",
    authorAr: 'أبو الحسن الأشعري',
    authorFr: "Abu al-Hasan al-Ash'ari",
    categoryId: 'aqida',
    pages: 180,
    year: '324 هـ',
    isOpenAccess: true,
    shamela_id: 45,
    description: "Œuvre fondatrice de la théologie ash'arite — l'Ash'ari y revient à une approche plus textualiste.",
  },
  {
    id: 'dar-taarus',
    titleAr: 'درء تعارض العقل والنقل',
    titleFr: "Dar' Ta'arud al-'Aql wa al-Naql",
    authorAr: 'أحمد بن تيمية الحراني',
    authorFr: 'Ahmad ibn Taymiyya al-Harrani',
    categoryId: 'aqida',
    volumes: 11,
    year: '728 هـ',
    isOpenAccess: true,
    description: "Réfutation de la doctrine de la priorité de la raison sur le texte — monumentale critique du kalam.",
  },

  // ══════════════════════════════════════════════
  // SIRA ET HISTOIRE
  // ══════════════════════════════════════════════
  {
    id: 'sira-ibn-hisham',
    titleAr: 'السيرة النبوية',
    titleFr: 'Sira de Ibn Hisham',
    authorAr: 'ابن هشام المعافري',
    authorFr: 'Abu Muhammad ibn Hisham al-Ma\'afiri',
    categoryId: 'sira',
    volumes: 4,
    year: '218 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 50,
    description: "La Sira du Prophète ﷺ — référence biographique fondamentale, édition d'Ibn Ishaq.",
    incipit: 'بسم الله الرحمن الرحيم قال ابن هشام: هذه سيرة رسول الله',
  },
  {
    id: 'rahiq-makhtum',
    titleAr: 'الرحيق المختوم',
    titleFr: 'Al-Rahiq al-Makhtum',
    authorAr: 'صفي الرحمن المباركفوري',
    authorFr: 'Safi al-Rahman al-Mubarakpuri',
    categoryId: 'sira',
    pages: 580,
    year: '1427 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 51,
    description: "Primé par la Ligue islamique mondiale — Sira moderne exhaustive et accessible en arabe.",
  },
  {
    id: 'sira-ibn-ishaq',
    titleAr: 'سيرة ابن إسحاق',
    titleFr: 'Sira de Ibn Ishaq',
    authorAr: 'محمد بن إسحاق المطلبي',
    authorFr: 'Muhammad ibn Ishaq al-Muttalibi',
    categoryId: 'sira',
    volumes: 3,
    year: '151 هـ',
    isOpenAccess: true,
    description: "La plus ancienne Sira — source originale transmise via Ibn Hisham, reconstructiion fragmentaire.",
  },
  {
    id: 'nur-yaqin',
    titleAr: 'نور اليقين في سيرة سيد المرسلين',
    titleFr: 'Nur al-Yaqin',
    authorAr: 'محمد الخضري بك',
    authorFr: 'Muhammad al-Khudari Bek',
    categoryId: 'sira',
    pages: 380,
    year: '1345 هـ',
    isOpenAccess: true,
    description: "Sira classique et bien structurée — enseignée dans les écoles islamiques depuis des décennies.",
  },
  {
    id: 'shamail-muhammadiyya',
    titleAr: 'الشمائل المحمدية',
    titleFr: 'Al-Shamail al-Muhammadiyya',
    authorAr: 'أبو عيسى الترمذي',
    authorFr: "Abu 'Isa al-Tirmidhi",
    categoryId: 'sira',
    pages: 300,
    year: '279 هـ',
    isOpenAccess: true,
    shamela_id: 52,
    description: "Description physique et morale du Prophète ﷺ — recueil unique de 400 hadiths descriptifs.",
  },
  {
    id: 'bidaya-nihaya',
    titleAr: 'البداية والنهاية',
    titleFr: 'Al-Bidaya wa al-Nihaya',
    authorAr: 'ابن كثير الدمشقي',
    authorFr: 'Ismail ibn Kathir al-Dimashqi',
    categoryId: 'sira',
    volumes: 14,
    year: '774 هـ',
    isOpenAccess: true,
    shamela_id: 53,
    description: "Histoire universelle islamique — de la création jusqu'à l'époque d'Ibn Kathir.",
  },
  {
    id: 'tarikh-tabari',
    titleAr: 'تاريخ الرسل والملوك',
    titleFr: 'Tarikh al-Tabari',
    authorAr: 'ابن جرير الطبري',
    authorFr: 'Muhammad ibn Jarir al-Tabari',
    categoryId: 'sira',
    volumes: 11,
    year: '310 هـ',
    isOpenAccess: true,
    shamela_id: 54,
    description: "Histoire universelle depuis la création — source primaire incontournable pour l'histoire islamique.",
  },
  {
    id: 'wafayat-ayan',
    titleAr: 'وفيات الأعيان وأنباء أبناء الزمان',
    titleFr: "Wafayat al-A'yan",
    authorAr: 'أبو العباس ابن خلكان',
    authorFr: 'Abu al-Abbas Ibn Khallikan',
    categoryId: 'sira',
    volumes: 7,
    year: '681 هـ',
    isOpenAccess: true,
    description: "Dictionnaire biographique des personnalités marquantes — 865 biographies détaillées.",
  },

  // ══════════════════════════════════════════════
  // TASAWWUF ET ÉTHIQUE
  // ══════════════════════════════════════════════
  {
    id: 'ihya-ulum',
    titleAr: 'إحياء علوم الدين',
    titleFr: "Ihya' 'Ulum al-Din",
    authorAr: 'أبو حامد الغزالي',
    authorFr: 'Abu Hamid al-Ghazali',
    categoryId: 'tasawwuf',
    volumes: 4,
    year: '505 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 60,
    description: "Chef-d'œuvre de la spiritualité islamique — encyclopédie du cœur et réforme intérieure.",
    incipit: 'الحمد لله الذي شرح صدور أوليائه بنور الإيمان',
  },
  {
    id: 'minhaj-qasideen',
    titleAr: 'منهاج القاصدين ومفيد الصادقين',
    titleFr: 'Minhaj al-Qasidin',
    authorAr: 'أحمد بن قدامة المقدسي',
    authorFr: "Ahmad ibn Qudama al-Maqdisi",
    categoryId: 'tasawwuf',
    pages: 400,
    year: '689 هـ',
    isOpenAccess: true,
    shamela_id: 61,
    description: "Abrégé de l'Ihya' de Ghazali adapté à la méthode hanbalie — spiritualité sans soufisme polémique.",
  },
  {
    id: 'risala-qushayriyya',
    titleAr: 'الرسالة القشيرية في علم التصوف',
    titleFr: 'Risala al-Qushayriyya',
    authorAr: 'أبو القاسم القشيري',
    authorFr: 'Abu al-Qasim al-Qushayri',
    categoryId: 'tasawwuf',
    pages: 600,
    year: '465 هـ',
    isOpenAccess: true,
    shamela_id: 62,
    description: "Traité fondateur du soufisme orthodoxe — présente 83 maîtres soufis et leurs enseignements.",
  },
  {
    id: 'madarij-salikin',
    titleAr: 'مدارج السالكين بين منازل إياك نعبد وإياك نستعين',
    titleFr: 'Madarij al-Salikin',
    authorAr: 'ابن قيم الجوزية',
    authorFr: 'Ibn Qayyim al-Jawziyya',
    categoryId: 'tasawwuf',
    volumes: 3,
    year: '751 هـ',
    isOpenAccess: true,
    shamela_id: 63,
    description: "Les stations du chemin vers Dieu — commentaire sur le Manazil al-Sa'irin d'al-Harawi.",
  },
  {
    id: 'hikam-ataiyya',
    titleAr: 'الحكم العطائية',
    titleFr: "Al-Hikam d'Ibn Ata Allah",
    authorAr: 'أحمد ابن عطاء الله الإسكندري',
    authorFr: "Ahmad Ibn Ata' Allah al-Iskandari",
    categoryId: 'tasawwuf',
    pages: 200,
    year: '709 هـ',
    isOpenAccess: true,
    shamela_id: 64,
    description: "Aphorismes mystiques parmi les plus beaux de la littérature soufie — traduits en de nombreuses langues.",
    incipit: 'من علامات الاعتماد على العمل نقصان الرجاء عند وجود الزلل',
  },
  {
    id: 'qut-qulub',
    titleAr: 'قوت القلوب في معاملة المحبوب',
    titleFr: 'Qut al-Qulub',
    authorAr: 'أبو طالب المكي',
    authorFr: 'Abu Talib al-Makki',
    categoryId: 'tasawwuf',
    volumes: 2,
    year: '386 هـ',
    isOpenAccess: true,
    description: "Précurseur de l'Ihya' de Ghazali — traité spirituel fondamental de la tradition soufie classique.",
  },
  {
    id: 'risala-mustazrafa',
    titleAr: 'الرسالة المستظرفة',
    titleFr: 'Al-Risala al-Mustazrafa',
    authorAr: 'محمد بن جعفر الكتاني',
    authorFr: 'Muhammad ibn Ja\'far al-Kattani',
    categoryId: 'tasawwuf',
    pages: 320,
    year: '1345 هـ',
    isOpenAccess: true,
    description: "Bibliographie des recueils de hadith — outil de référence pour les étudiants en sciences du hadith.",
  },

  // ══════════════════════════════════════════════
  // LANGUE ARABE
  // ══════════════════════════════════════════════
  {
    id: 'alfiyya-ibn-malik',
    titleAr: 'ألفية ابن مالك في النحو والصرف',
    titleFr: "Alfiyya d'Ibn Malik",
    authorAr: 'جمال الدين ابن مالك الأندلسي',
    authorFr: 'Jamal al-Din Ibn Malik al-Andalusi',
    categoryId: 'lughah',
    pages: 120,
    year: '672 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 70,
    description: "1000 vers sur la grammaire arabe — le texte de grammaire le plus mémorisé dans le monde islamique.",
    incipit: 'قال محمد هو ابن مالك أحمد ربي الله خير مالك',
  },
  {
    id: 'sharh-alfiyya-ibn-aqil',
    titleAr: 'شرح الألفية لابن عقيل',
    titleFr: "Sharh al-Alfiyya d'Ibn Aqil",
    authorAr: 'بهاء الدين ابن عقيل المصري',
    authorFr: "Baha' al-Din Ibn 'Aqil al-Misri",
    categoryId: 'lughah',
    volumes: 2,
    year: '769 هـ',
    isOpenAccess: true,
    shamela_id: 71,
    description: "Le commentaire le plus utilisé de l'Alfiyya — clarté pédagogique exceptionnelle.",
  },
  {
    id: 'kafiya-shafiya',
    titleAr: 'الكافية الشافية',
    titleFr: "Al-Kafiya al-Shafiya d'Ibn Malik",
    authorAr: 'جمال الدين ابن مالك الأندلسي',
    authorFr: 'Jamal al-Din Ibn Malik al-Andalusi',
    categoryId: 'lughah',
    pages: 180,
    year: '672 هـ',
    isOpenAccess: true,
    description: "Version étendue de l'Alfiyya en 3000 vers — couverture exhaustive de la grammaire arabe.",
  },
  {
    id: 'ajurrumiyya',
    titleAr: 'الآجرومية',
    titleFr: "Al-Ajurrumiyya",
    authorAr: 'أبو عبد الله ابن آجروم الصنهاجي',
    authorFr: 'Abu Abdallah Ibn Ajurrum al-Sanhaji',
    categoryId: 'lughah',
    pages: 30,
    year: '723 هـ',
    isOpenAccess: true,
    shamela_id: 72,
    description: "Texte d'introduction à la grammaire arabe — le plus enseigné dans le monde islamique pour débutants.",
    incipit: 'بسم الله الرحمن الرحيم. الكلام هو اللفظ المركب المفيد',
  },
  {
    id: 'qatr-nada',
    titleAr: 'قطر الندى وبل الصدى',
    titleFr: "Qatr al-Nada d'Ibn Hisham",
    authorAr: 'جمال الدين ابن هشام الأنصاري',
    authorFr: 'Jamal al-Din Ibn Hisham al-Ansari',
    categoryId: 'lughah',
    pages: 200,
    year: '761 هـ',
    isOpenAccess: true,
    shamela_id: 73,
    description: "Texte de grammaire intermédiaire — entre l'Ajurrumiyya et l'Alfiyya, très pédagogique.",
  },
  {
    id: 'mughni-labib',
    titleAr: 'مغني اللبيب عن كتب الأعاريب',
    titleFr: "Mughni al-Labib d'Ibn Hisham",
    authorAr: 'جمال الدين ابن هشام الأنصاري',
    authorFr: 'Jamal al-Din Ibn Hisham al-Ansari',
    categoryId: 'lughah',
    volumes: 2,
    year: '761 هـ',
    isOpenAccess: true,
    shamela_id: 74,
    description: "Référence sur les particules et la syntaxe arabe — outil indispensable pour l'analyse grammaticale.",
  },
  {
    id: 'mufassal-zamakhshari',
    titleAr: 'المفصل في صنعة الإعراب',
    titleFr: "Al-Mufassal de al-Zamakhshari",
    authorAr: 'جار الله الزمخشري',
    authorFr: 'Jar Allah al-Zamakhshari',
    categoryId: 'lughah',
    pages: 450,
    year: '538 هـ',
    isOpenAccess: true,
    description: "Grammaire exhaustive en prose — une des œuvres grammaticales les plus influentes du Moyen Âge.",
  },
  {
    id: 'lisan-arab',
    titleAr: 'لسان العرب',
    titleFr: "Lisan al-Arab d'Ibn Manzur",
    authorAr: 'ابن منظور الأفريقي',
    authorFr: 'Ibn Manzur al-Ifriqi',
    categoryId: 'lughah',
    volumes: 15,
    year: '711 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 75,
    description: "Le plus grand dictionnaire de la langue arabe classique — 80 000 entrées lexicales.",
  },
  {
    id: 'qamus-muhit',
    titleAr: 'القاموس المحيط',
    titleFr: "Al-Qamus al-Muhit de al-Fayruzabadi",
    authorAr: 'مجد الدين الفيروزابادي',
    authorFr: 'Majd al-Din al-Fayruzabadi',
    categoryId: 'lughah',
    volumes: 4,
    year: '817 هـ',
    isOpenAccess: true,
    shamela_id: 76,
    description: "Dictionnaire classique compact — source primaire du Taj al-Arus de Zabidi.",
  },
  {
    id: 'taj-arus',
    titleAr: 'تاج العروس من جواهر القاموس',
    titleFr: "Taj al-'Arus de al-Zabidi",
    authorAr: 'محمد مرتضى الزبيدي',
    authorFr: 'Muhammad Murtada al-Zabidi',
    categoryId: 'lughah',
    volumes: 40,
    year: '1205 هـ',
    isOpenAccess: true,
    shamela_id: 77,
    description: "Le plus vaste dictionnaire arabe — commentaire exhaustif du Qamus al-Muhit en 40 volumes.",
  },

  // ══════════════════════════════════════════════
  // DIVERS (Encyclopédies, Usul al-Fiqh, etc.)
  // ══════════════════════════════════════════════
  {
    id: 'muqaddima-ibn-khaldun',
    titleAr: 'مقدمة ابن خلدون',
    titleFr: "Muqaddima d'Ibn Khaldun",
    authorAr: 'عبد الرحمن بن خلدون',
    authorFr: 'Abd al-Rahman ibn Khaldun',
    categoryId: 'general',
    pages: 800,
    year: '808 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 80,
    description: "Fondement de la sociologie historique — œuvre unique de philosophie de l'histoire islamique.",
    incipit: 'فصل في أن الاجتماع الإنساني ضروري',
  },
  {
    id: 'kitab-umm',
    titleAr: 'كتاب الأم',
    titleFr: "Kitab al-Umm d'al-Shafi'i",
    authorAr: 'محمد بن إدريس الشافعي',
    authorFr: "Muhammad ibn Idris al-Shafi'i",
    categoryId: 'general',
    volumes: 8,
    year: '204 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 81,
    description: "L'œuvre maîtresse de l'imam al-Shafi'i — fondement du madhab shafi'i et de l'usul al-fiqh.",
    incipit: 'الحمد لله الذي هدانا للإسلام',
  },
  {
    id: 'muwafaqat-shatibi',
    titleAr: 'الموافقات في أصول الشريعة',
    titleFr: "Al-Muwafaqat d'al-Shatibi",
    authorAr: 'أبو إسحاق الشاطبي',
    authorFr: "Abu Ishaq al-Shatibi",
    categoryId: 'general',
    volumes: 4,
    year: '790 هـ',
    isOpenAccess: true,
    shamela_id: 82,
    description: "Théorie des maqasid al-shari'a — œuvre révolutionnaire de philosophie du droit islamique.",
  },
  {
    id: 'ihkam-amidi',
    titleAr: 'الإحكام في أصول الأحكام',
    titleFr: "Al-Ihkam fi Usul al-Ahkam d'al-Amidi",
    authorAr: 'سيف الدين الآمدي',
    authorFr: 'Sayf al-Din al-Amidi',
    categoryId: 'general',
    volumes: 4,
    year: '631 هـ',
    isOpenAccess: true,
    description: "Traité systématique d'usul al-fiqh — méthode rationaliste ash'arite, haute technicité.",
  },
  {
    id: 'rawdat-nazir',
    titleAr: 'روضة الناظر وجنة المناظر',
    titleFr: "Rawdat al-Nazir d'Ibn Qudama",
    authorAr: 'ابن قدامة المقدسي',
    authorFr: 'Ibn Qudama al-Maqdisi',
    categoryId: 'general',
    pages: 400,
    year: '620 هـ',
    isOpenAccess: true,
    shamela_id: 83,
    description: "Introduction à l'usul al-fiqh hanbali — texte d'enseignement classique et clair.",
  },
  {
    id: 'risala-shafi',
    titleAr: 'الرسالة',
    titleFr: "Al-Risala d'al-Shafi'i",
    authorAr: 'محمد بن إدريس الشافعي',
    authorFr: "Muhammad ibn Idris al-Shafi'i",
    categoryId: 'general',
    pages: 350,
    year: '204 هـ',
    isOpenAccess: true,
    shamela_id: 84,
    description: "Premier traité d'usul al-fiqh de l'histoire — fondation de la méthodologie juridique islamique.",
    incipit: 'الحمد لله الذي هدانا للإيمان',
  },
  {
    id: 'tahrir-taqrib',
    titleAr: 'التحرير والتنوير',
    titleFr: "Al-Tahrir wa al-Tanwir",
    authorAr: 'محمد الطاهر بن عاشور',
    authorFr: 'Muhammad al-Tahir ibn Ashur',
    categoryId: 'quran',
    volumes: 30,
    year: '1393 هـ',
    isOpenAccess: true,
    description: "Tafsir encyclopédique moderne tunisien — mêle linguistique, droit et philosophie religieuse.",
  },
  {
    id: 'fi-zilal-quran',
    titleAr: 'في ظلال القرآن',
    titleFr: "Fi Zilal al-Qur'an",
    authorAr: 'سيد قطب',
    authorFr: 'Sayyid Qutb',
    categoryId: 'quran',
    volumes: 6,
    year: '1387 هـ',
    isOpenAccess: true,
    shamela_id: 8,
    description: "Tafsir littéraire et spirituel du XXe siècle — rédigé en partie en prison, très diffusé.",
  },
  {
    id: 'mukhtasar-khalil',
    titleAr: 'مختصر خليل',
    titleFr: "Mukhtasar Khalil",
    authorAr: 'خليل بن إسحاق الجندي',
    authorFr: 'Khalil ibn Ishaq al-Jundi',
    categoryId: 'fiqh',
    pages: 250,
    year: '776 هـ',
    isOpenAccess: true,
    shamela_id: 31,
    description: "Matn de référence du madhab malékite — texte le plus commenté dans l'Afrique du Nord.",
  },
  {
    id: 'iqna-hajawi',
    titleAr: 'الإقناع لطالب الانتفاع',
    titleFr: "Al-Iqna' d'al-Hajawi",
    authorAr: 'موسى بن أحمد الحجاوي المقدسي',
    authorFr: 'Musa ibn Ahmad al-Hajawi al-Maqdisi',
    categoryId: 'fiqh',
    volumes: 2,
    year: '968 هـ',
    isOpenAccess: true,
    shamela_id: 32,
    description: "Matn de référence hanbali — commenté dans la célèbre Kashaf al-Qina' de al-Bahuti.",
  },
  {
    id: 'tabaqat-kubra',
    titleAr: 'الطبقات الكبرى',
    titleFr: "Al-Tabaqat al-Kubra d'Ibn Sa'd",
    authorAr: 'محمد بن سعد الزهري',
    authorFr: 'Muhammad ibn Sa\'d al-Zuhri',
    categoryId: 'sira',
    volumes: 8,
    year: '230 هـ',
    isOpenAccess: true,
    description: "Premières biographies systématiques des compagnons du Prophète ﷺ — source primaire inestimable.",
  },
  {
    id: 'fath-bari',
    titleAr: 'فتح الباري شرح صحيح البخاري',
    titleFr: "Fath al-Bari — Sharh Sahih al-Bukhari",
    authorAr: 'ابن حجر العسقلاني',
    authorFr: 'Ibn Hajar al-Asqalani',
    categoryId: 'hadith',
    volumes: 17,
    year: '852 هـ',
    isOpenAccess: true,
    isFeatured: true,
    shamela_id: 13,
    description: "Le commentaire de référence du Sahih al-Bukhari — 25 ans de travail, érudition inégalée.",
  },
  {
    id: 'nawawi-sharh-muslim',
    titleAr: 'شرح النووي على صحيح مسلم',
    titleFr: "Sharh al-Nawawi 'ala Sahih Muslim",
    authorAr: 'يحيى بن شرف النووي',
    authorFr: 'Yahya ibn Sharaf al-Nawawi',
    categoryId: 'hadith',
    volumes: 18,
    year: '676 هـ',
    isOpenAccess: true,
    shamela_id: 14,
    description: "Commentaire fondamental du Sahih Muslim — richesse du fiqh et de la langue arabique.",
  },
  {
    id: 'isaba-sahabah',
    titleAr: 'الإصابة في تمييز الصحابة',
    titleFr: "Al-Isaba fi Tamyiz al-Sahaba",
    authorAr: 'ابن حجر العسقلاني',
    authorFr: 'Ibn Hajar al-Asqalani',
    categoryId: 'sira',
    volumes: 8,
    year: '852 هـ',
    isOpenAccess: true,
    shamela_id: 55,
    description: "Dictionnaire biographique des compagnons du Prophète ﷺ — 12 000 notices biographiques.",
  },
  {
    id: 'maqasid-sharia',
    titleAr: 'مقاصد الشريعة الإسلامية',
    titleFr: "Maqasid al-Shari'a al-Islamiyya",
    authorAr: 'محمد الطاهر بن عاشور',
    authorFr: 'Muhammad al-Tahir ibn Ashur',
    categoryId: 'general',
    pages: 450,
    year: '1393 هـ',
    isOpenAccess: true,
    description: "Traité moderne sur les finalités de la loi islamique — œuvre de référence en philosophie du droit.",
  },
  {
    id: 'tawil-mushkil',
    titleAr: 'تأويل مشكل القرآن',
    titleFr: "Ta'wil Mushkil al-Qur'an",
    authorAr: 'أبو محمد ابن قتيبة الدينوري',
    authorFr: 'Abu Muhammad Ibn Qutayba al-Dinawari',
    categoryId: 'quran',
    pages: 500,
    year: '276 هـ',
    isOpenAccess: true,
    description: "Réponse aux critiques du Coran — traité de défense du texte coranique et ses apparentes difficultés.",
  },
]

// ── Fonctions ────────────────────────────────────────────────

export function getAllCategories(): LibraryCategory[] {
  return LIBRARY_CATEGORIES
}

export function getCategoryById(id: string): LibraryCategory | undefined {
  return LIBRARY_CATEGORIES.find(c => c.id === id)
}

export function getAllBooks(): LibraryBook[] {
  return FEATURED_BOOKS
}

export function getFeaturedBooks(categoryId?: string): LibraryBook[] {
  if (categoryId) {
    return FEATURED_BOOKS.filter(b => b.categoryId === categoryId)
  }
  return FEATURED_BOOKS.filter(b => b.isFeatured)
}

export function getBooksByCategory(categoryId: string): LibraryBook[] {
  return FEATURED_BOOKS.filter(b => b.categoryId === categoryId)
}

export function getBookById(id: string): LibraryBook | undefined {
  return FEATURED_BOOKS.find(b => b.id === id)
}

export function getRelatedBooks(book: LibraryBook, limit = 3): LibraryBook[] {
  return FEATURED_BOOKS
    .filter(b => b.id !== book.id && b.categoryId === book.categoryId)
    .slice(0, limit)
}

export function getBooksByAuthor(authorAr: string, excludeId?: string): LibraryBook[] {
  return FEATURED_BOOKS.filter(
    b => b.authorAr === authorAr && b.id !== excludeId
  )
}

export function searchBooks(query: string): LibraryBook[] {
  if (!query.trim()) return []
  const q = query.toLowerCase().trim()
  return FEATURED_BOOKS.filter(b => {
    return (
      b.titleAr.includes(query) ||
      (b.titleFr?.toLowerCase().includes(q)) ||
      b.authorAr.includes(query) ||
      (b.authorFr?.toLowerCase().includes(q)) ||
      (b.description?.toLowerCase().includes(q))
    )
  })
}

export function getTotalBooksCount(): number {
  return LIBRARY_CATEGORIES.reduce((sum, c) => sum + c.bookCount, 0)
}

/**
 * URL Shamela pour un livre si on a son ID
 */
export function getShamela_url(shamelaId: number): string {
  return `https://shamela.ws/book/${shamelaId}`
}

/**
 * URL Archive.org pour un livre (recherche par titre)
 */
export function getArchiveUrl(titleAr: string): string {
  return `https://archive.org/search?query=${encodeURIComponent(titleAr)}`
}

/**
 * URL Islamhouse (recherche)
 */
export function getIslamhouseUrl(titleFr?: string, titleAr?: string): string {
  const q = titleFr ?? titleAr ?? ''
  return `https://islamhouse.com/fr/search/?q=${encodeURIComponent(q)}`
}
